version: '3.9'

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/linkify
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET_KEY=XbGD1T2HrTLncAAnhsTlJ+0WvodFnGmALB7Qcr8PlTI=

  postgres:
    container_name: postgres
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=linkify
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "linkify", "-U", "admin"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
