version: '3.9'

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/linkify
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_PROPERTIES_HIBERNATE_GENERATE_STATISTICS=true
      - JWT_SECRET_KEY=XbGD1T2HrTLncAAnhsTlJ+0WvodFnGmALB7Qcr8PlTI=
      - LOG_CONFIG=dev
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully

  postgres:
    container_name: postgres
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=linkify
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

  flyway:
    container_name: flyway
    image: flyway/flyway:10.7.2-alpine
    command: migrate
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/linkify
      - FLYWAY_USER=admin
      - FLYWAY_PASSWORD=admin
      - FLYWAY_SCHEMAS=public
      - FLYWAY_CONNECT_RETRIES=10
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

networks:
  default:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: 127.0.0.1

volumes:
  postgres-data:
