spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: ${SPRING_JPA_PROPERTIES_HIBERNATE_HBM2DDL_AUTO}
        generate_statistics: ${SPRING_JPA_PROPERTIES_HIBERNATE_GENERATE_STATISTICS}
        log_slow_query: 10

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
